# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc0c73057b1e215eabf5fb8ec358c8a034759f3c22c0473dcb30cf70ddff7d68c139b24f17370fc8d5d1704bbed058598378acb9314782cdab67404a8b1e1964

test:
  secret_key_base: 8469c355bd506197f0293c2ee6c57ef2d2818d97ff9f674c81f0e468a8bdb4e86f99b8ce987558fe4c429b47100741b8b61ef113b0a841eb3918e50c687f6bd2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
